name: shared
description: A package that stores shared components, models and logic.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  equatable: ^2.0.5
  fast_immutable_collections: ^10.2.3
  flutter:
    sdk: flutter
  hive: ^2.2.3
  intl: ^0.19.0
  logger: ^2.3.0
  papa_burger_server:
    git: https://github.com/Gambley1/papa-burger-server.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
