name: user_repository
description: A repository that manages user data flow.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  authentication_client:
    path: ../authentication_client/authentication_client
  equatable: ^2.0.5
  rxdart: ^0.27.7
  storage:
    path: ../storage/storage
  yandex_food_api:
    path: ../../api

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^6.0.0
