# include: package:flutter_lints/flutter.yaml
include: package:very_good_analysis/analysis_options.4.0.0.yaml
analyzer:
  exclude:
    - build/**

linter:
  rules:
    file_names: false
    use_super_parameters: true
    public_member_api_docs: false
    sort_pub_dependencies: false
