name: yandex_food_delivery_clone
description: A new Flutter project.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.22.0

dependencies:
  animations: ^2.0.11
  app_ui:
    path: packages/app_ui
  badges: ^3.1.2
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  env:
    path: packages/env
  equatable: ^2.0.5
  fast_immutable_collections: ^10.2.4
  firebase_authentication_client:
    path: packages/authentication_client/firebase_authentication_client
  firebase_core: ^3.0.0
  flexible_wrap: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_credit_card: ^4.0.1
  flutter_stripe: ^11.0.0
  form_fields:
    path: packages/form_fields
  formz: ^0.4.1
  geocode: ^1.0.3
  go_router: ^13.2.5
  google_maps_flutter: ^2.7.0
  hydrated_bloc: ^9.1.5
  intl: any
  json_annotation: ^4.9.0
  location_repository:
    path: packages/location_repository
  logger: ^2.3.0
  notifications_client:
    path: packages/notifications_client
  notifications_repository:
    path: packages/notifications_repository
  orders_repository:
    path: packages/orders_repository
  path_provider: ^2.1.3
  payments_repository:
    path: packages/payments_repository
  permission_client:
    path: packages/permission_client
  persistent_storage:
    path: packages/storage/persistent_storage
  restaurants_repository:
    path: packages/restaurants_repository
  rxdart: ^0.27.7
  shadcn_ui: ^0.8.0
  shared:
    path: packages/shared
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  stripe_payments_client:
    path: packages/payments_client/stripe_payments_client
  token_storage:
    path: packages/authentication_client/token_storage
  url_launcher: ^6.3.0
  user_repository:
    path: packages/user_repository
  web_socket_client: ^0.1.4
  yandex_food_api:
    path: api

dev_dependencies:
  build_runner: ^2.4.11
  build_verify: ^3.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0

dependency_overrides:
  intl: ^0.19.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/papa-burger.png"
  adaptive_icon_foreground: "assets/images/papa_burger_ic_launcher_adaptive_fore.png"
  adaptive_icon_background: "assets/images/papa_burger_ic_launcher_adaptive_back.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
