name: papa_burger
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  # sdk: ">=3.0.0 <3.1.0"

dependencies:
  flutter:
    sdk: flutter

  papa_burger_server:
    git: https://github.com/Gambley1/papa-burger-server

  cupertino_icons: ^1.0.5
  page_transition: ^2.0.9
  google_fonts: ^4.0.4
  shimmer: ^2.0.0
  formz: ^0.4.1
  font_awesome_flutter: ^10.4.0
  flutter_credit_card: ^3.0.6
  flutter_spinkit: ^5.2.0
  # google_nav_bar: ^5.0.6
  
  connectivity_plus: ^4.0.0
  dio: ^5.1.2
  
  rxdart: ^0.27.7
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.6

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.1.1
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.3
  
  google_sign_in: ^6.1.0
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  fast_immutable_collections: ^9.1.1
  logger: ^1.3.0
  flutter_svg: ^2.0.5
  provider: ^6.0.5
  stream_loader: ^1.5.0
  device_preview: ^1.1.0
  device_preview_screenshot: ^1.0.0
  appwrite: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  json_serializable: ^6.6.2
  build_runner: ^2.4.4
  # flutter_lints: ^2.0.1
  very_good_analysis: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/