name: papa_burger
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  papa_burger_server:
    git: https://github.com/Gambley1/papa-burger-server.git

  cupertino_icons: ^1.0.2
  page_transition: ^2.0.9
  google_fonts: ^3.0.1
  shimmer: ^2.0.0
  formz: ^0.4.1
  font_awesome_flutter: ^10.3.0
  flutter_credit_card: ^3.0.6
  flutter_spinkit: ^5.1.0
  # google_nav_bar: ^5.0.6
  
  connectivity_plus: ^3.0.3
  dio: ^5.1.1
  
  rxdart: ^0.27.7
  equatable: ^2.0.5
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2

  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.4

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.15
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.3
  
  google_sign_in: ^5.4.2
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.3
  fast_immutable_collections: ^8.2.0
  logger: ^1.1.0
  flutter_svg: ^2.0.5
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  json_serializable: ^6.6.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/