name: papa_burger
description: A new Flutter project.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.22.0

dependencies:
  app_ui:
    path: packages/app_ui
  background_fetch: ^1.3.2
  badges: ^3.1.2
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  equatable: ^2.0.5
  faker: ^2.1.0
  fast_immutable_collections: ^10.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_cache_manager: ^3.3.1
  flutter_credit_card: ^4.0.1
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^16.3.2
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  form_fields:
    path: packages/form_fields
  formz: ^0.4.1
  geocoding: ^2.2.0
  geolocator: ^11.0.0
  google_fonts: ^6.2.0
  google_maps_flutter: ^2.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: any
  logger: ^2.0.2+1
  page_transition: ^2.1.0
  papa_burger_server:
    git: https://github.com/Gambley1/papa-burger-server.git
  permission_handler: ^11.3.0
  rxdart: ^0.27.7
  shadcn_ui: ^0.4.7
  shared:
    path: packages/shared
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  web_socket_client: ">=0.1.0-dev.3 <=0.1.1"

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

dependency_overrides:
  intl: ^0.19.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/papa-burger.png"
  adaptive_icon_foreground: "assets/images/papa_burger_ic_launcher_adaptive_fore.png"
  adaptive_icon_background: "assets/images/papa_burger_ic_launcher_adaptive_back.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
