final Map<String, String> _countryCodeMap = {
  'Andorra: Principality Of': 'AD',
  'United Arab Emirates': 'AE',
  'Afghanistan Islamic State Of': 'AF',
  'Antigua And Barbuda': 'AG',
  'Anguilla': 'AI',
  'Albania': 'AL',
  'Armenia': 'AM',
  'Netherlands Antilles': 'AN',
  'Angola': 'AO',
  'Antarctica': 'AQ',
  'Argentina': 'AR',
  'American Samoa': 'AS',
  'Austria': 'AT',
  'Australia': 'AU',
  'Aruba': 'AW',
  'Azerbaidjan': 'AZ',
  'Bosnia-Herzegovina': 'BA',
  'Barbados': 'BB',
  'Bangladesh': 'BD',
  'Belgium': 'BE',
  'Burkina Faso': 'BF',
  'Bulgaria': 'BG',
  'Bahrain': 'BH',
  'Burundi': 'BI',
  'Benin': 'BJ',
  'Bermuda': 'BM',
  'Brunei Darussalam': 'BN',
  'Bolivia': 'BO',
  'Brazil': 'BR',
  'Bahamas': 'BS',
  'Bhutan': 'BT',
  'Bouvet Island': 'BV',
  'Botswana': 'BW',
  'Belarus': 'BY',
  'Belize': 'BZ',
  'Canada': 'CA',
  'Cocos (Keeling) Islands': 'CC',
  'Central African Republic': 'CF',
  'Congo: The Democratic Republic Of The': 'CD',
  'Congo': 'CG',
  'Switzerland': 'CH',
  "Ivory Coast (Cote D'Ivoire)": 'CI',
  'Cook Islands': 'CK',
  'Chile': 'CL',
  'Cameroon': 'CM',
  'China': 'CN',
  'Colombia': 'CO',
  'Costa Rica': 'CR',
  'Former Czechoslovakia': 'CS',
  'Cuba': 'CU',
  'Cape Verde': 'CV',
  'Christmas Island': 'CX',
  'Cyprus': 'CY',
  'Czech Republic': 'CZ',
  'Germany': 'DE',
  'Djibouti': 'DJ',
  'Denmark': 'DK',
  'Dominica': 'DM',
  'Dominican Republic': 'DO',
  'Algeria': 'DZ',
  'Ecuador': 'EC',
  'Estonia': 'EE',
  'Egypt': 'EG',
  'Western Sahara': 'EH',
  'Eritrea': 'ER',
  'Spain': 'ES',
  'Ethiopia': 'ET',
  'Finland': 'FI',
  'Fiji': 'FJ',
  'Falkland Islands': 'FK',
  'Micronesia': 'FM',
  'Faroe Islands': 'FO',
  'France': 'FR',
  'France (European Territory)': 'FX',
  'Gabon': 'GA',
  'Great Britain': 'UK',
  'Grenada': 'GD',
  'Georgia': 'GE',
  'French Guyana': 'GF',
  'Ghana': 'GH',
  'Gibraltar': 'GI',
  'Greenland': 'GL',
  'Gambia': 'GM',
  'Guinea': 'GN',
  'Guadeloupe (French)': 'GP',
  'Equatorial Guinea': 'GQ',
  'Greece': 'GR',
  'S. Georgia & S. Sandwich Isls.': 'GS',
  'Guatemala': 'GT',
  'Guam (USA)': 'GU',
  'Guinea Bissau': 'GW',
  'Guyana': 'GY',
  'Hong Kong': 'HK',
  'Heard And McDonald Islands': 'HM',
  'Honduras': 'HN',
  'Croatia': 'HR',
  'Haiti': 'HT',
  'Hungary': 'HU',
  'Indonesia': 'ID',
  'Ireland': 'IE',
  'Israel': 'IL',
  'India': 'IN',
  'British Indian Ocean Territory': 'IO',
  'Iraq': 'IQ',
  'Iran': 'IR',
  'Iceland': 'IS',
  'Italy': 'IT',
  'Jamaica': 'JM',
  'Jordan': 'JO',
  'Japan': 'JP',
  'Kenya': 'KE',
  'Kyrgyz Republic (Kyrgyzstan)': 'KG',
  'Cambodia: Kingdom Of': 'KH',
  'Kiribati': 'KI',
  'Comoros': 'KM',
  'Saint Kitts & Nevis Anguilla': 'KN',
  'North Korea': 'KP',
  'South Korea': 'KR',
  'Kuwait': 'KW',
  'Cayman Islands': 'KY',
  'Kazakhstan': 'KZ',
  'Laos': 'LA',
  'Lebanon': 'LB',
  'Saint Lucia': 'LC',
  'Liechtenstein': 'LI',
  'Sri Lanka': 'LK',
  'Liberia': 'LR',
  'Lesotho': 'LS',
  'Lithuania': 'LT',
  'Luxembourg': 'LU',
  'Latvia': 'LV',
  'Libya': 'LY',
  'Morocco': 'MA',
  'Monaco': 'MC',
  'Moldavia': 'MD',
  'Madagascar': 'MG',
  'Marshall Islands': 'MH',
  'Macedonia': 'MK',
  'Mali': 'ML',
  'Myanmar': 'MM',
  'Mongolia': 'MN',
  'Macau': 'MO',
  'Northern Mariana Islands': 'MP',
  'Martinique (French)': 'MQ',
  'Mauritania': 'MR',
  'Montserrat': 'MS',
  'Malta': 'MT',
  'Mauritius': 'MU',
  'Maldives': 'MV',
  'Malawi': 'MW',
  'Mexico': 'MX',
  'Malaysia': 'MY',
  'Mozambique': 'MZ',
  'Namibia': 'NA',
  'New Caledonia (French)': 'NC',
  'Niger': 'NE',
  'Norfolk Island': 'NF',
  'Nigeria': 'NG',
  'Nicaragua': 'NI',
  'Netherlands': 'NL',
  'Norway': 'NO',
  'Nepal': 'NP',
  'Nauru': 'NR',
  'Neutral Zone': 'NT',
  'Niue': 'NU',
  'New Zealand': 'NZ',
  'Oman': 'OM',
  'Panama': 'PA',
  'Peru': 'PE',
  'Polynesia (French)': 'PF',
  'Papua New Guinea': 'PG',
  'Philippines': 'PH',
  'Pakistan': 'PK',
  'Poland': 'PL',
  'Saint Pierre And Miquelon': 'PM',
  'Pitcairn Island': 'PN',
  'Puerto Rico': 'PR',
  'Portugal': 'PT',
  'Palau': 'PW',
  'Paraguay': 'PY',
  'Qatar': 'QA',
  'Reunion (French)': 'RE',
  'Romania': 'RO',
  'Russian Federation': 'RU',
  'Rwanda': 'RW',
  'Saudi Arabia': 'SA',
  'Solomon Islands': 'SB',
  'Seychelles': 'SC',
  'Sudan': 'SD',
  'Sweden': 'SE',
  'Singapore': 'SG',
  'Saint Helena': 'SH',
  'Slovenia': 'SI',
  'Svalbard And Jan Mayen Islands': 'SJ',
  'Slovak Republic': 'SK',
  'Sierra Leone': 'SL',
  'San Marino': 'SM',
  'Senegal': 'SN',
  'Somalia': 'SO',
  'Suriname': 'SR',
  'Saint Tome (Sao Tome) And Principe': 'ST',
  'Former USSR': 'SU',
  'El Salvador': 'SV',
  'Syria': 'SY',
  'Swaziland': 'SZ',
  'Turks And Caicos Islands': 'TC',
  'Chad': 'TD',
  'French Southern Territories': 'TF',
  'Togo': 'TG',
  'Thailand': 'TH',
  'Tadjikistan': 'TJ',
  'Tokelau': 'TK',
  'Turkmenistan': 'TM',
  'Tunisia': 'TN',
  'Tonga': 'TO',
  'East Timor': 'TP',
  'Turkey': 'TR',
  'Trinidad And Tobago': 'TT',
  'Tuvalu': 'TV',
  'Taiwan': 'TW',
  'Tanzania': 'TZ',
  'Ukraine': 'UA',
  'Uganda': 'UG',
  'United Kingdom': 'UK',
  'USA Minor Outlying Islands': 'UM',
  'United States': 'US',
  'Uruguay': 'UY',
  'Uzbekistan': 'UZ',
  'Holy See (Vatican City State)': 'VA',
  'Saint Vincent & Grenadines': 'VC',
  'Venezuela': 'VE',
  'Virgin Islands (British)': 'VG',
  'Virgin Islands (USA)': 'VI',
  'Vietnam': 'VN',
  'Vanuatu': 'VU',
  'Wallis And Futuna Islands': 'WF',
  'Samoa': 'WS',
  'Yemen': 'YE',
  'Mayotte': 'YT',
  'Yugoslavia': 'YU',
  'South Africa': 'ZA',
  'Zambia': 'ZM',
  'Zaire': 'ZR',
  'Zimbabwe': 'ZW',
};

/// Country code string parser.
extension CountryCodeExtension on String {
  String getCountryCode() {
    return _countryCodeMap[this] ?? '';
  }
}
