name: payments_repository
description: A repository that manages payments data flow.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  stripe_payments_client:
    path: ../payments_client/stripe_payments_client
  yandex_food_api:
    path: ../../api

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^6.0.0
