name: location_repository
description: A repository that manages user location.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^6.0.0

dependencies:
  dio: ^5.5.0+1
  env:
    path: ../env
  geolocator: ^12.0.0
  shared:
    path: ../shared
