// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS6hZ6Kr-n5MtyB15bxpVa1t3ai0i2kko',
    appId: '1:381757361898:web:34cbc98911b2328dc89193',
    messagingSenderId: '381757361898',
    projectId: 'papa-burger',
    authDomain: 'papa-burger.firebaseapp.com',
    storageBucket: 'papa-burger.appspot.com',
    measurementId: 'G-L9JJX7EYC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpduAH-GFwI1zzv3RCwvvveyDP7JsSink',
    appId: '1:381757361898:android:dd1b7b11e832fb43c89193',
    messagingSenderId: '381757361898',
    projectId: 'papa-burger',
    storageBucket: 'papa-burger.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMSY3ZgqCZOsDwETyKkt0FodJ6DAokQM0',
    appId: '1:381757361898:ios:8923b021075a6783c89193',
    messagingSenderId: '381757361898',
    projectId: 'papa-burger',
    storageBucket: 'papa-burger.appspot.com',
    iosClientId: '381757361898-6c3r2jpldq9qfgu2eo3v49bp0k4dna01.apps.googleusercontent.com',
    iosBundleId: 'com.example.papaBurger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMSY3ZgqCZOsDwETyKkt0FodJ6DAokQM0',
    appId: '1:381757361898:ios:8923b021075a6783c89193',
    messagingSenderId: '381757361898',
    projectId: 'papa-burger',
    storageBucket: 'papa-burger.appspot.com',
    iosClientId: '381757361898-6c3r2jpldq9qfgu2eo3v49bp0k4dna01.apps.googleusercontent.com',
    iosBundleId: 'com.example.papaBurger',
  );
}
