name: form_fields
description: A package that manages form fields like email, password etc.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  formz: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
