name: env
description: A package that manages application secrets.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.4.0"

dev_dependencies:
  build_runner: ^2.4.11
  envied_generator: ^0.5.4
  mocktail: ^1.0.3
  test: ^1.25.7
  very_good_analysis: ^5.1.0
  
dependencies:
  envied: ^0.5.4
