name: notifications_repository
description: A repository that manages notifications with web socket.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^6.0.0

dependencies:
  notifications_client:
    path: ../notifications_client
  permission_client:
    path: ../permission_client
  storage:
    path: ../storage/storage
  user_repository:
    path: ../user_repository
  web_socket_client: ^0.1.4
