include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.schema.dart
linter:
  rules:
    file_names: false
    avoid_print: false
    public_member_api_docs: false
