name: yandex_food_api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bcrypt: ^1.1.3
  broadcast_bloc: ^0.1.0-dev.2
  dart_frog: ^1.1.0
  dart_frog_web_socket: ^1.0.0
  dart_jsonwebtoken: ^2.14.0
  dio: ^5.4.3
  dotenv: ^4.2.0
  env:
    path: packages/env
  equatable: ^2.0.5
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.3.0
  shelf_cors_headers: ^0.1.5
  stormberry: ^0.14.0
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
